export const EMPTY_FORM_STATE = {
  id: '',
  name: '',
  slug: '',
  enrollments: 0,
  certified: 0,
  completionRate: 0,
  supportEmail: '',
  emailRegexes: [],
  courseEnrollmentLimit: 0,
  userLimit: 0,
  availableStartDate: new Date(),
  availableEndDate: new Date(),
  catalogAlternativeLink: '',
  isSelfEnrollment: false,
  customCourses: false,
  authorizationAdditionalMessage: '',
  isPublic: false,
  courses: 0,
  corporatePartner: 0,
};
